# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "MonitorHandle",
    "get_global_metrics",
    "get_process_metrics",
]

@typing.final
class MonitorHandle:
    r"""
    Holds the shared state to allow Python to stop the Rust background thread.
    """
    ...

def get_global_metrics() -> tuple[builtins.float, builtins.str, builtins.float, builtins.int, builtins.float, builtins.int, builtins.int]:
    r"""
    Grab a single snapshot of the current global CPU, RAM usage percentage, available disk space in bytes, and boot time.
    """

def get_process_metrics(name: builtins.str) -> builtins.list[tuple[builtins.int, builtins.float, builtins.float]]:
    r"""
    Grab usage metrics for specific processes by name.
    """

